//OPTIONS FOR QUESTIONNAIRE
export const interestsOptions = [
  { answer: "Outdoor", image: "../assets/images/outdoor.png" },
  { answer: "Fitness", image: "../assets/images/fitness.png" },
  { answer: "Health", image: "../assets/images/healthCare.png" },
  { answer: "Travel", image: "../assets/images/travel.png" },
  { answer: "Theme parks", image: "../assets/images/themeParks.png" },
  { answer: "Cooking", image: "../assets/images/cooking.png" },
  { answer: "Sports", image: "../assets/images/sports.png" },
  { answer: "Adventure", image: "../assets/images/adventure.png" },
  { answer: "Music", image: "../assets/images/music.png" },
  { answer: "Fashion", image: "../assets/images/fashion.png" },
  { answer: "Technology", image: "../assets/images/technology.png" },
  { answer: "Architecture", image: "../assets/images/architecture.png" },
  { answer: "Writting", image: "../assets/images/writting.png" },
  { answer: "Gaming", image: "../assets/images/gaming.png" },
  { answer: "Dining", image: "../assets/images/dining.png" },
  { answer: "History", image: "../assets/images/history.png" },
  { answer: "Theatre", image: "../assets/images/theatre.png" },
  { answer: "Networking", image: "../assets/images/networking.png" },
  { answer: "Art", image: "../assets/images/art.png" },
  { answer: "Politics", image: "../assets/images/politics.png" },
  { answer: "Fishing", image: "../assets/images/fishing.png" },
  { answer: "Meet People", image: "../assets/images/meetPeople.png" },
  { answer: "Podcast", image: "../assets/images/podcast.png" },
  { answer: "Gambling", image: "../assets/images/gambling.png" },
  { answer: "Self improvement", image: "../assets/images/yes.png" },
  {
    answer: "Foreign languages",
    image: "../assets/images/foreignLanguage.png",
  },
  { answer: "Movies", image: "../assets/images/movies.png" },
  { answer: "Celebrities", image: "../assets/images/fashion.png" },
  { answer: "Dating", image: "../assets/images/dating.png" },
  { answer: "Social media", image: "../assets/images/socialMedia.png" },
  { answer: "Photography", image: "../assets/images/media.png" },
];

export const reasonsOptions = [
  {
    answer: "Lifestyle",
    image: import("../assets/images/lifestyle.png"),
  },
  {
    answer: "Work opportunities",
    image: "../assets/images/workOpportunity.png",
  },
  { answer: "Education", image: "../assets/images/education.png" },
  { answer: "Finance", image: "../assets/images/finance.png" },
  { answer: "Tourism", image: "../assets/images/tourism.png" },
  { answer: "Family", image: "../assets/images/family.png" },
  { answer: "Business", image: "../assets/images/business.png" },
  { answer: "Security", image: "../assets/images/security.png" },
  { answer: "The Weather", image: "../assets/images/weather.png" },
  { answer: "Meeting new ppeople", image: "../assets/images/newPeople.png" },
  { answer: "Culture", image: "../assets/images/culture.png" },
];

export const specialtiesOptions = [
  { answer: "Construction", image: "../assets/images/construction.png" },
  { answer: "Hospitality", image: "../assets/images/hospitality.png" },
  { answer: "Real Estate", image: "../assets/images/realEstate.png" },
  { answer: "Tourism", image: "../assets/images/tourism.png" },
  { answer: "Manufacturing", image: "../assets/images/manufacturing.png" },
  { answer: "Technology", image: "../assets/images/technology.png" },
  { answer: "Media", image: "../assets/images/media.png" },
  { answer: "Farming", image: "../assets/images/farming.png" },
  { answer: "Fishing", image: "../assets/images/fishing.png" },
  { answer: "Education", image: "../assets/images/education.png" },
  { answer: "Public service", image: "../assets/images/publicService.png" },
  { answer: "Administration", image: "../assets/images/administration.png" },
  {
    answer: "Financial services",
    image: "../assets/images/financialServices.png",
  },
  { answer: "Legal", image: "../assets/images/legal.png" },
  { answer: "Health care", image: "../assets/images/healthCare.png" },
  { answer: "Government", image: "../assets/images/government.png" },
  { answer: "Medical", image: "../assets/images/medical.png" },
  { answer: "Security", image: "../assets/images/security.png" },
  { answer: "Logistics", image: "../assets/images/logistics.png" },
  { answer: "Robotics", image: "../assets/images/robotics.png" },
  { answer: "Fashion", image: "../assets/images/fashion.png" },
  { answer: "Automative", image: "../assets/images/automotive.png" },
  { answer: "Transportation", image: "../assets/images/transportation.png" },
  { answer: "Customer support", image: "../assets/images/customerSupport.png" },
];

export const savingsOptions = [
  { answer: "No savings", image: "../assets/images/zeroCoin.png" },
  { answer: "0 to 1000 aed", image: "../assets/images/oneCoin.png" },
  { answer: "1000 to 5000 aed", image: "../assets/images/twoCoins.png" },
  { answer: "5000 to 10000 aed", image: "../assets/images/threeCoins.png" },
  { answer: "10,000 to 20,000 aed", image: "../assets/images/fourCoins..png" },
  { answer: "20,000 to 50,000 aed", image: "../assets/images/fiveCoins.png" },
  { answer: "+50,000 aed", image: "../assets/images/sixCoins.png" },
];

export const educationOptions = [
  { answer: "High school or less", image: "../assets/images/highSchool.png" },
  { answer: "College", image: "../assets/images/college.png" },
  { answer: "Diploma", image: "../assets/images/diploma.png" },
  { answer: "Bachelors", image: "../assets/images/bachelors.png" },
];

export const timeToArrivalOptions = [
  { answer: "Right now", image: "../assets/images/calendar.png" },
  { answer: "0 to 3 months", image: "../assets/images/calendar.png" },
  { answer: "3 to 6 months", image: "../assets/images/calendar.png" },
  { answer: "6 - 12 months", image: "../assets/images/calendar.png" },
  { answer: "After 1 year", image: "../assets/images/calendar.png" },
  { answer: "I'm not sure", image: "../assets/images/calendar.png" },
];

export const getInitialInterests = () => {
  const obj = {};
  for (const key of interestsOptions) {
    obj[key] = false;
  }
  return obj;
};

//COUNTRIES LIST
export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];
